name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # Pushed tags starting with 'v' (e.g., v1.0.0)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rinzlerfr/idena-node:latest
      
    - name: Docker Push latest
      run: docker push rinzlerfr/idena-node:latest

    - name: Docker Push with tag name
      run: docker push rinzlerfr/idena-node:${{ github.ref }}
