name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # Pushed tags starting with 'v' (e.g., v1.0.0)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract tag name
      id: extract_tag
      run: echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}
      
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: docker build
      run: |
        docker build -t idena-node . \
        --tag rinzlerfr/idena-node:quicktest \
        --tag rinzlerfr/idena-node:latest \
        --tag rinzlerfr/idena-node:${{ steps.extract_tag.outputs.tag_name }}
    
    - name: Quick Test
      run: |
        docker run --env RUN_TIMEOUT=3 --rm rinzlerfr/idena-node:quicktest
        returnedCode=$?

        if [ $returnedCode -eq 124 ]; then
            exit 0
        fi

        exit $returnedCode
    
    - name: docker push
      run: |
        docker push rinzlerfr/idena-node:latest
        docker push rinzlerfr/idena-node:${{ steps.extract_tag.outputs.tag_name }}
